# Site settings
title: Hassan Kotb
description: 'Business Card Page'
url: 'https://www.zuehlke.cloud'
baseurl: ''
profilepic: '/images/pch.jpg'
bkimage: '/images/bkh.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '320e57d55c.js'

author:
  name: 'Hassan Kotb'
  email: hassankotb410@gmail.com
  mastodon: tzuehlke@mstdn.social
  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  Hasnkotb
  linkedin_username:  hassan-m-kotb
  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
